version: '3.9'

services:
  db:
    build:
      dockerfile: ./Docker/db.dockerfile
      context: .
    environment:
      SA_PASSWORD: Qwerty12345!
      DB_NAME: cms
    ports:
      - 6000:1433
    volumes:
      - ./App_Data:/var/opt/mssql/host_data
    image: alloy-docker/db
  web:
    depends_on:
      - db
    build:
      dockerfile: ./Docker/web.dockerfile
      context: .
    environment:
      ASPNETCORE_URLS: http://*:80
      ASPNETCORE_ENVIRONMENT: Development
      CONNECTIONSTRINGS__EPISERVERDB: Server=db,1433;Database=cms;User Id=sa;Password=Qwerty12345!;Encrypt=False;
    ports:
      - 6001:80
    volumes:
      - .:/src
    image: alloy-docker/web
    restart: on-failure
